update msg styles

diff --git a/bin/error_msg b/bin/error_msg
--- a/bin/error_msg
+++ b/bin/error_msg
@@ -4,5 +4,5 @@ color_red='\e[31m'
 color_yellow='\e[33m'
 color_default='\e[39m'
 
-echo -e "${color_red}error${color_default}: ${@}" 1>&2
+echo -e "${color_red}[ERROR]${color_default}\t${@}" 1>&2
 exit 1
