update scripts to use {error,warning}_msg function

diff --git a/bin/eval_cmd b/bin/eval_cmd
--- a/bin/eval_cmd
+++ b/bin/eval_cmd
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-red='\e[31m'
-yellow='\e[33m'
-nocolor='\e[39m'
+# red='\e[31m'
+# yellow='\e[33m'
+# nocolor='\e[39m'
  
 # ------------------------------------------------------------------------------
 # usage
@@ -31,15 +31,16 @@ usage() {
             show this help message and exit
         
 USAGE
-    exit 1
+    # exit 1
 }
 
 # ------------------------------------------------------------------------------
 # parse usage
 # ------------------------------------------------------------------------------
 if [ $# -eq 0 ]; then
-        usage
-    fi
+    usage
+    exit 1
+fi
 
 # default values
 overwrite=0
@@ -65,10 +66,11 @@ while [[ $# -gt 0 ]]; do
             ;;
         -h|--help)
             usage
+            exit 0
             ;;
         *)
-            echo "Unknown argument: $1"
             usage
+            bash error_msg "unrecognized option: $1"
             ;;
     esac
 done
@@ -78,14 +80,17 @@ done
 # ------------------------------------------------------------------------------
 echo -e "\ncommand:\n${cmd}\n"
 if [[ ${print} -eq 1 ]]; then
-    echo -e "${yellow}warning${nocolor}: printing, but not running command"
+    # echo -e "${yellow}warning${nocolor}: printing, but not running command"
+    bash warning_msg "printing, but not running command"
     exit 0
 fi
 
 if [[ -f ${out_path} ]] && [[ ${overwrite} -eq 0 ]]; then
-    echo -e "${yellow}warning${nocolor}: skipping, file already exists and overwrite set to 0 (${out_path})"
+    # echo -e "${yellow}warning${nocolor}: skipping, file already exists and overwrite set to 0 (${out_path})"
+    bash warning_msg "skipping, file already exists and overwrite set to 0 (${out_path})"
 elif [[ -f ${out_path} ]] && [[ ${overwrite} -eq 1 ]]; then
-    echo -e "${yellow}warning${nocolor}: overwriting, file already exists and overwrite set to 1 (${out_path})"
+    # echo -e "${yellow}warning${nocolor}: overwriting, file already exists and overwrite set to 1 (${out_path})"
+    bash warning_msg "overwriting, file already exists and overwrite set to 1 (${out_path})"
     rm ${out_path}
     eval ${cmd}
 elif [[ ! -f ${out_path} ]]; then
@@ -93,6 +98,7 @@ elif [[ ! -f ${out_path} ]]; then
 fi
 
 if [[ ! -f ${out_path} ]]; then
-    echo -e "${red}error${nocolor}: output file not generated (${out_path})"
-    exit 1
+    # echo -e "${red}error${nocolor}: output file not generated (${out_path})"
+    # exit 1
+    bash error_msg "output file not generated (${out_path})"
 fi
diff --git a/bin/get_airc_id_from_sub_ses b/bin/get_airc_id_from_sub_ses
--- a/bin/get_airc_id_from_sub_ses
+++ b/bin/get_airc_id_from_sub_ses
@@ -7,21 +7,24 @@ ses=$2
 # check for input
 # ------------------------------------------------------------------------------
 if [[ -z ${sub} ]]; then
-    echo "ERROR: sub is a required argument"
-    echo "   USAGE: ${0} <sub> <ses>"
-    exit 1
+    # echo "ERROR: sub is a required argument"
+    # echo "   USAGE: ${0} <sub> <ses>"
+    # exit 1
+    bash error_msg "sub is a required argument\n\tUSAGE: ${0} <sub> <ses>"
 fi
 
 if [[ -z ${ses} ]]; then
-    echo "ERROR: ses is a required argument"
-    echo "   USAGE: ${0} <sub> <ses>"
-    exit 1
+    # echo "ERROR: ses is a required argument"
+    # echo "   USAGE: ${0} <sub> <ses>"
+    # exit 1
+    bash error_msg "ses is a required argument\n\tUSAGE: ${0} <sub> <ses>"
 fi
 
 if [[ ${ses} -lt 1 ]]; then 
-    echo "ERROR: ses must be greater than 0"
-    echo "   USAGE: ${0} <sub> <ses>"
-    exit 1
+    # echo "ERROR: ses must be greater than 0"
+    # echo "   USAGE: ${0} <sub> <ses>"
+    # exit 1
+    bash error_msg "ses must be greater than 0\n\tUSAGE: ${0} <sub> <ses>"
 fi
 
 # ------------------------------------------------------------------------------
@@ -44,12 +47,14 @@ done
 
 # checks
 if [[ ${#airc_ids[@]} -eq 0 ]]; then
-    >&2 echo "ERROR: no airc ids found for sub-${sub} and ses-${ses}"
-    exit 1
+    # >&2 echo "ERROR: no airc ids found for sub-${sub} and ses-${ses}"
+    # exit 1
+    bash error_msg "no airc ids found for sub-${sub} and ses-${ses}"
 fi
 
 if [[ ${#airc_ids[@]} -gt 1 ]]; then
-    >&2 echo "WARNING: multiple airc ids found for sub-${sub} and ses-${ses}"
+    # >&2 echo "WARNING: multiple airc ids found for sub-${sub} and ses-${ses}"
+    bash warning_msg "multiple airc ids found for sub-${sub} and ses-${ses}"
 fi
 
 # print
diff --git a/bin/get_ses_from_airc_id b/bin/get_ses_from_airc_id
--- a/bin/get_ses_from_airc_id
+++ b/bin/get_ses_from_airc_id
@@ -8,8 +8,9 @@ root_dir=`${code_dir}/get_root_dir kenrod`
 ses=`cat ${root_dir}/incoming/ids_long-format.csv | grep ${airc_id} | awk -F ',' '{print $3}'`
 
 if [[ -z ${ses} ]] || [[ ${ses} == 'NA' ]]; then
-    echo "error: session/wave could not be found for ${airc_id}" 1>&2
-    exit 1
+    # echo "error: session/wave could not be found for ${airc_id}" 1>&2
+    # exit 1
+    bash error_msg "session/wave could not be found for ${airc_id}"
 fi
 
 echo ${ses}
