update flags to allow for slurm pe

diff --git a/bin/flex_wrapper b/bin/flex_wrapper
--- a/bin/flex_wrapper
+++ b/bin/flex_wrapper
@@ -10,45 +10,48 @@ usage() {
 
     Options:
         
-        --in_scripts <path>     (required)
+        --in-scripts, --in_scripts <path>       (required)
             path to text file of scripts to wrap
                 inside the text file has a new line for each script to run
         
-        --in_ids <path>         (required)
+        --in-ids, --in_ids <path>               (required)
             path to csv with subject and session list
                 columns: sub, ses, (airc_id)
 
-        --scripts_idx           (required)
+        --scripts-idx, --scripts_idx            (required)
             script to process:
                 <int1>,<int2>,...       multiple inputs separated by commas (e.g., -s 1,2,3)
                 <int_start>:<int_end>   range of scripts to process (e.g., -s 1:3)
                 'all'                   process all scripts
 
-        --ids_idx               (required)
+        --ids-idx, --ids_idx                     (required)
             idx of ids to process:
                 <int1>,<int2>,...       multiple inputs separated by commas (e.g., -s 1,2,3)
                 <int_start>:<int_end>   range of scripts to process (e.g., -s 1:3)
                 'all'                   process all scripts
 
-        --sge <0|1>             (optional)
-            whether to run on SGE (1) or not (0) (default: 0)
+        --parallel <0|sge|slurm>                 (optional)
+            whether to run in parallel
+                0       no parallelization, runs serially (default)
+                sge     SGE
+                slurm   SLURM
 
-        --sge_job_limit <int>   (optional)
+        --parallel-opts, --parallel_opts <str>   (optional)
+            additional flags/options to pass to parallel engine
+
+        --parallel-job-limit, --parallel_job_limit <int>   (optional)
             maximum number of jobs to running on SGE (default: 0, i.e. no limit)
 
-        --sge_server <0|1|2>    (optional)
-            which SGE server to use (default: 0)
-                0. both
+        --sge-server, --sge_server <0|1|2>       (optional)
+            which SGE server to use
+                0. both (defult)
                 1. ponyo
                 2. totoro
 
-        --sge_flags <str>         (optional)
-            additional flags/options to pass to SGE
-
-        --print <0|1>           (optional)
+        --print <0|1>                            (optional)
             print commands to screen only (default: 0)
 
-        --overwrite <0|1>       (optional)
+        --overwrite <0|1>                        (optional)
             flag to overwrite existing output files (default: 0)
 
         -h, --help
@@ -89,6 +92,9 @@ sge_server=0
 sge_job_limit=0
 test=0
 overwrite=0
+color_red='\033[0;31m'
+color_yellow='\033[0;33m'
+color_default='\033[0m'
 
 # ------------------------------------------------------------------------------
 # parse args
@@ -102,41 +108,42 @@ fi
 # parse command line arguments
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        --in_scripts)
+        --in_scripts|--in-scripts)
             in_scripts=$2
             shift 2
             ;;
-        --in_ids)
+        --in_ids|--in-ids)
             in_ids=$2
             shift 2
             ;;
-        --scripts_idx)
+        --scripts_idx|--scripts-idx)
             scripts_idx=$2
             shift 2
             ;;
-        --ids_idx)
+        --ids_idx|--ids-idx)
             ids_idx=$2
             shift 2
             ;;
-        --sge)
-            sge=$2
-            if [[ ${sge} -eq 0 ]] || [[ ${sge} -eq 1 ]]; then
+        --parallel)
+            parallel=$2
+            if [[ ${parallel} == "0" ]] || [[ ${parallel} == "sge" ]] || [[ ${parallel} == "slurm" ]]; then
                 shift 2
             else
-                echo "error: --sge must be 0 or 1"
+                usage
+                echo -e "${color_red}error${color_default}: --parallel must be 0, sge, or slurm"
                 exit 1
             fi
             ;;
-        --sge_job_limit)
-            sge_job_limit=$2
+        --parallel_opts|--parallel-opts)
+            parallel_opts=$2
+            shift 2
+            ;;
+        --parallel_job_limit|--parallel-job-limit)
+            parallel_job_limit=$2
             shift 2
             ;;
         --sge_server)
             sge_server=$2
-            shift 2
-            ;;
-        --sge_flags)
-            sge_flags=$2
             shift 2
             ;;
         --print)
@@ -163,28 +170,28 @@ done
 # check args
 # ------------------------------------------------------------------------------
 if [[ -z ${in_scripts} ]]; then
-    echo -e "\nerror: must specify --in_scripts"
     usage
+    echo -e "\n${color_red}error${color_default}: must specify --in_scripts"
     exit 1
 fi
 
 if [[ -z ${in_ids} ]]; then
-    echo -e "\nerror: must specify --in_ids"
     usage
+    echo -e "\n${color_red}error${color_default}: must specify --in_ids"
     exit 1
 fi
 
 if [[ -z ${scripts_idx} ]]; then
     usage
     usage_scripts_idx
-    echo -e "\nerror: must specify --scripts_idx\n"
+    echo -e "\n${color_red}error${color_default}: must specify --scripts_idx\n"
     exit 1
 fi
 
 if [[ -z ${ids_idx} ]]; then
     usage
     usage_ids_idx
-    echo -e "\nerror: must specify --ids_idx\n"
+    echo -e "\n${color_red}error${color_default}: must specify --ids_idx\n"
     exit 1
 fi
 
@@ -193,7 +200,7 @@ fi
 # ------------------------------------------------------------------------------
 in_scripts=(`cat ${in_scripts}`)
 if [[ ${#in_scripts[@]} -eq 0 ]]; then
-    echo "error: no scripts found in ${in_scripts}"
+    echo -e "\n${color_red}error${color_default}: no scripts found in ${in_scripts}"
     exit 1
 fi
 
@@ -208,8 +215,6 @@ elif [[ ${scripts_idx} == *","* ]]; then
 else
     scripts_idx=(`echo ${scripts_idx}`)
 fi
-
-
 
 # adjust scripts_idx to 0-based
 for i in ${!scripts_idx[@]}; do
@@ -231,10 +236,15 @@ done
 # ------------------------------------------------------------------------------
 # read ids
 # ------------------------------------------------------------------------------
+id_cols=(`head -n 1 ${in_ids} | sed 's/,/ /g'`)
+id_cols_alt=`head -n 1 ${in_ids}`
+# echo ${id_cols[@]}
+# exit 1
 in_ids=(`cat ${in_ids}`)
+# id_cols=(`awk -F ',' '{print $1}' ${in_ids}`)
 
 if [[ ${#in_ids[@]} -eq 0 ]]; then
-    echo "error: no ids found in ${in_ids}"
+    echo -e "\n${color_red}error${color_default}: no ids found in ${in_ids}"
     exit 1
 fi
 
@@ -267,23 +277,39 @@ done
 # exit 1
 
 # ------------------------------------------------------------------------------
-# non-sge option
+# parallel: 0 (serial)
 # ------------------------------------------------------------------------------
-
-if [[ ${sge} -eq 0 ]]; then
-    echo -e "\nscript_idx,id_idx,airc_id,sub,ses"
+if [[ ${parallel} == "0" ]]; then
+    echo -e "\nscript_idx,id_idx,${id_cols_alt}"
     for s in ${!scripts[@]}; do
         for i in ${!ids[@]}; do
             id=${ids[$i]}
             s1=`echo ${s} + 1 | bc`
             i1=`echo ${i} + 1 | bc`
             echo -e "\n${s1},${i1},${ids[$i]}"
+
+            # ---
+            # flex options
+            # not working, but not sure why
+            # ---
+            # id_i=(`echo ${ids[${i}]} | sed 's/,/ /g'`)
+            # opts=""
+            # for j in ${!id_cols[@]}; do
+            #     opts="${opts}--${id_cols[${j}]} ${id_i[${j}]} "
+            # done
+            # opts="${opts}--overwrite ${overwrite}"
+
+            # ---
+            # fixed options
+            # ---
             airc_id=`echo ${id} | awk -F, '{print $1}'`
             sub=`echo ${id} | awk -F, '{print $2}'`
             ses=`echo ${id} | awk -F, '{print $3}'`
-            opts="--airc_id ${airc_id} --sub ${sub} --ses ${ses} --overwrite ${overwrite}"
+            study=`echo ${id} | awk -F, '{print $4}'`
+            opts="--study ${study} --airc_id ${airc_id} --sub ${sub} --ses ${ses} --overwrite ${overwrite}"
+            
             cmd="bash ${scripts[${s}]} ${opts}"
-            echo -e "command:\n${cmd}"
+            echo -e "\ncommand:\n${cmd}\n"
             if [[ ${print} -eq 0 ]]; then
                 eval ${cmd}
             fi
@@ -292,10 +318,16 @@ if [[ ${sge} -eq 0 ]]; then
 fi
 
 # ------------------------------------------------------------------------------
-# sge option
+# parallel: sge
 # ------------------------------------------------------------------------------
-if [[ ${sge} -eq 1 ]]; then
-    echo -e "\nscript_idx,id_idx,airc_id,sub,ses"
+# sge_default_opts="-V \
+# -S /bin/bash \
+# -j y \
+# -m a \
+# -M ${USER}@utdallas.edu"
+
+if [[ ${parallel} == 'sge' ]]; then
+    echo -e "\nscript_idx,id_idx,${id_cols_alt}"
     module load sge
     declare -a job_id_list
     c=0
@@ -306,11 +338,25 @@ if [[ ${sge} -eq 1 ]]; then
             i1=`echo ${i} + 1 | bc`
             echo -e "\n${s1},${i1},${ids[$i]}"
             
+            # ---
+            # flex options
+            # not working, but not sure why
+            # ---
+            # id_i=(`echo ${ids[$i]} | sed 's/,/ /g'`)
+            # opts=""
+            # for j in ${!id_cols[@]}; do
+            #     opts="${opts}--${id_cols[$j]} ${id_i[$j]} "
+            # done
+            # opts="${opts}--overwrite ${overwrite}"
+
+            # ---
+            # fixed options
+            # ---
             airc_id=`echo ${id} | awk -F, '{print $1}'`
             sub=`echo ${id} | awk -F, '{print $2}'`
             ses=`echo ${id} | awk -F, '{print $3}'`
-
-            opts="--airc_id ${airc_id} --sub ${sub} --ses ${ses} --overwrite ${overwrite}"
+            study=`echo ${id} | awk -F, '{print $4}'`
+            opts="--study ${study} --airc_id ${airc_id} --sub ${sub} --ses ${ses} --overwrite ${overwrite}"
             
             script_name=`basename ${scripts[${s}]} | sed 's/.sh//'`
             job_name="sub-${sub}_ses-${ses}_script-${script_name}"
@@ -318,6 +364,7 @@ if [[ ${sge} -eq 1 ]]; then
 
             job_id_list[${c}]=${job_name}
             
+            # sge_opts=""
             sge_opts="-N ${job_name}"
 
             # sge server
@@ -327,16 +374,84 @@ if [[ ${sge} -eq 1 ]]; then
                 sge_opts="${sge_opts} -q all.q@cvlkrcompute2.utdallas.edu"
             fi
 
-            if [[ ! -z ${sge_flags} ]]; then
-                sge_opts="${sge_opts} ${sge_flags}"
+            if [[ ! -z ${parallel_opts} ]]; then
+                sge_opts="${sge_opts} ${parallel_opts}"
             fi
 
             # sge job limit
-            if [[ ${sge_job_limit} -gt 0 ]] && [[ ${c} -ge ${sge_job_limit} ]]; then
-                sge_opts="${sge_opts} -hold_jid ${job_id_list[$((c - sge_job_limit))]}"
+            if [[ ${parallel_job_limit} -gt 0 ]] && [[ ${c} -ge ${parallel_job_limit} ]]; then
+                sge_opts="${sge_opts} -hold_jid ${job_id_list[$((c - parallel_job_limit))]}"
             fi
 
             cmd="qsub ${sge_opts} ${scripts[$s]} ${opts}"
+        
+            echo -e "command:\n${cmd}"
+            if [[ ${print} -eq 0 ]]; then
+                eval ${cmd}
+            fi
+
+            c=`echo ${c} + 1 | bc`
+        done
+    done
+fi
+
+# ------------------------------------------------------------------------------
+# parallel: slurm
+# ------------------------------------------------------------------------------
+# slurm_opts="--shell=/bin/bash \
+# --output=jid-$SLURM_JOB_ID-$SLURM_ARRAY_TASK_ID_jname-$SLURM_JOB_NAME.log \
+# --error=jid-$SLURM_JOB_ID-$SLURM_ARRAY_TASK_ID_jname-$SLURM_JOB_NAME.log \
+# --mail-type=FAIL \
+# --mail-user=${USER}@utdallas.edu"
+
+if [[ ${parallel} == 'slurm' ]]; then
+    echo -e "\nscript_idx,id_idx,${id_cols_alt}"
+    declare -a job_id_list
+    c=0
+    for s in ${!scripts[@]}; do
+        for i in ${!ids[@]}; do
+            id=${ids[$i]}
+            s1=`echo ${s} + 1 | bc`
+            i1=`echo ${i} + 1 | bc`
+            echo -e "\n${s1},${i1},${ids[$i]}"
+            
+            # ---
+            # flex options
+            # not working, but not sure why
+            # ---
+            # id_i=(`echo ${ids[$i]} | sed 's/,/ /g'`)
+            # opts=""
+            # for j in ${!id_cols[@]}; do
+            #     opts="${opts}--${id_cols[$j]} ${id_i[$j]} "
+            # done
+            # opts="${opts}--overwrite ${overwrite}"
+
+            # ---
+            # fixed options
+            # ---
+            airc_id=`echo ${id} | awk -F, '{print $1}'`
+            sub=`echo ${id} | awk -F, '{print $2}'`
+            ses=`echo ${id} | awk -F, '{print $3}'`
+            study=`echo ${id} | awk -F, '{print $4}'`
+            opts="--study ${study} --airc_id ${airc_id} --sub ${sub} --ses ${ses} --overwrite ${overwrite}"
+            
+            script_name=`basename ${scripts[${s}]} | sed 's/.sh//'`
+            job_name="sub-${sub}_ses-${ses}_script-${script_name}"
+
+            job_id_list[${c}]=${job_name}
+            
+            slurm_opts="--job-name=${job_name}"
+
+            if [[ ! -z ${parallel_opts} ]]; then
+                slurm_opts="${slurm_opts} ${parallel_opts}"
+            fi
+
+            # sge job limit
+            if [[ ${parallel_job_limit} -gt 0 ]] && [[ ${c} -ge ${parallel_job_limit} ]]; then
+                slurm_opts="${slurm_opts} --dependency=afternotok:${job_id_list[$((c - parallel_job_limit))]}"
+            fi
+
+            cmd="sbatch ${slurm_opts} ${scripts[$s]} ${opts}"
         
             echo -e "command:\n${cmd}"
             if [[ ${print} -eq 0 ]]; then
