small edits

diff --git a/get_ses_from_airc_id b/get_ses_from_airc_id
--- a/get_ses_from_airc_id
+++ b/get_ses_from_airc_id
@@ -2,14 +2,21 @@
 
 airc_id=$1
 
-airc_id_number=`echo ${airc_id} | sed 's/3tb//g'`
+# airc_id_number=`echo ${airc_id} | sed 's/3tb//g'`
 
-if [[ ${airc_id_number} < 4188 ]]; then 
-    ses="1"
-elif [[ ${airc_id_number} > 4188 ]] && [[ ${airc_id_number} < 8000 ]]; then
-    ses="2"
-elif [[ ${airc_id_number} > 8000 ]]; then
-    ses="3"
+# if [[ ${airc_id_number} < 4188 ]]; then 
+#     ses="1"
+# elif [[ ${airc_id_number} > 4188 ]] && [[ ${airc_id_number} < 8000 ]]; then
+#     ses="2"
+# elif [[ ${airc_id_number} > 8000 ]]; then
+#     ses="3"
+# fi
+
+ses=`cat ${root_dir}/shared/incoming/ids_long-format.csv | grep ${airc_id} | awk -F ',' '{print $3}'`
+
+if [[ -z ${ses} ]] || [[ ${ses} == 'NA' ]]; then
+    echo "error: session/wave could not be found for ${airc_id}" 1>&2
+    exit 1
 fi
 
 echo ${ses}
